version: 2

updates:
  - package-ecosystem: bun
    commit-message:
      include: scope
      prefix: chore
    open-pull-requests-limit: 100
    cooldown:
      default-days: 5
    directory: /
    groups:
      astro:
        patterns:
          - "@astrojs/*"
          - "astro"
      cloudflare:
        patterns:
          - "@cloudflare/*"
          - "wrangler"
      commitlint:
        patterns:
          - "@commitlint/*"
      effect:
        patterns:
          - "@effect/*"
          - "effect"
      i18n:
        patterns:
          - "i18next"
          - "i18next-cli"
          - "react-i18next"
      playwright:
        patterns:
          - "@playwright/*"
          - "playwright"
      radix:
        patterns:
          - "@radix-ui/*"
      solana:
        patterns:
          - "@solana/*"
          - "@solana-program/*"
      tanstack-query:
        patterns:
          - "@tanstack/query-*"
          - "@tanstack/react-query*"
      turbo:
        patterns:
          - "@turbo/*"
          - "turbo"
      wallet-standard:
        patterns:
          - "@wallet-standard/*"
      webext-core:
        patterns:
          - "@webext-core/*"
      wxt:
        patterns:
          - "@wxt-dev/*"
          - "wxt"
    schedule:
      day: sunday
      interval: weekly
      time: "00:00"
      timezone: UTC

  - package-ecosystem: github-actions
    commit-message:
      include: scope
      prefix: chore
    open-pull-requests-limit: 100
    cooldown:
      default-days: 5
    directory: /
    schedule:
      day: sunday
      interval: weekly
      time: "00:00"
      timezone: UTC
