export const ACTIONS = Object.freeze({
  CONNECT: 'SAMUI_CONNECT',
  DISCONNECT: 'SAMUI_DISCONNECT',
  SIGN_AND_SEND_TRANSACTION: 'SAMUI_SIGN_AND_SEND_TRANSACTION',
  SIGN_IN: 'SAMUI_SIGN_IN',
  SIGN_MESSAGE: 'SAMUI_SIGN_MESSAGE',
  SIGN_TRANSACTION: 'SAMUI_SIGN_TRANSACTION',
})
