name: Publish pkg.pr.new

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Dependencies
        uses: ./.github/workflows/actions/install-dependencies

      - name: Build
        run: pnpm build

      - name: Publish to pkg.pr.new
        run: pnpm pkg-pr-new publish --pnpm --packageManager=pnpm './packages/*' --comment=off
